"""Initial schema: accounts, teams, matches, the delivery log, and tournaments.

Revision ID: 0001_initial
Revises:
Created: 2026-07-28

Notes for reviewers:

* Primary keys are UUIDs generated by Postgres (``gen_random_uuid()``, built in
  from PG13 onward, which covers every current Neon project). Client-generated
  ids would also work, but server defaults keep raw SQL inserts honest.
* Enum-ish columns are ``VARCHAR`` + ``CHECK`` rather than native PG enums:
  adding a new wicket type or match format is then an ordinary migration instead
  of an ``ALTER TYPE`` that cannot run inside a transaction.
* ``delivery_revisions.delivery_id`` deliberately has **no** foreign key: the
  correction log has to survive the deletion of the ball it describes.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("user", "admin", name="user_role", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_email_verified", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    # Case-insensitive uniqueness without a generated column.
    op.create_index(
        "uq_users_email_lower", "users", [sa.literal_column("lower(email)")], unique=True
    )

    op.create_table(
        "audit_logs",
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "action",
            sa.Enum(
                "user.registered",
                "user.login",
                "user.login_failed",
                "user.logout",
                "user.password_changed",
                "auth.token_reuse_detected",
                "match.created",
                "match.updated",
                "match.deleted",
                "match.completed",
                "delivery.recorded",
                "delivery.edited",
                "delivery.deleted",
                "innings.started",
                "innings.closed",
                "tournament.created",
                "tournament.updated",
                name="audit_action",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("entity_type", sa.String(length=40), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=256), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(
        "ix_audit_logs_actor_created", "audit_logs", ["actor_user_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(
        "ix_audit_logs_entity", "audit_logs", ["entity_type", "entity_id"], unique=False
    )

    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_reason", sa.String(length=64), nullable=True),
        sa.Column("replaced_by_id", sa.UUID(), nullable=True),
        sa.Column("user_agent", sa.String(length=256), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by_id"],
            ["refresh_tokens.id"],
            name=op.f("fk_refresh_tokens_replaced_by_id_refresh_tokens"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name="uq_refresh_tokens_token_hash"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_created_at"), "refresh_tokens", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_expires_at"), "refresh_tokens", ["expires_at"], unique=False
    )
    op.create_index("ix_refresh_tokens_family", "refresh_tokens", ["family_id"], unique=False)
    op.create_index(
        "ix_refresh_tokens_user_active", "refresh_tokens", ["user_id", "revoked_at"], unique=False
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)

    op.create_table(
        "teams",
        sa.Column("owner_user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("short_name", sa.String(length=6), nullable=True),
        sa.Column("logo_url", sa.String(length=512), nullable=True),
        sa.Column("primary_color", sa.String(length=9), nullable=True),
        sa.Column("home_ground", sa.String(length=120), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_teams_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
    )
    op.create_index(op.f("ix_teams_created_at"), "teams", ["created_at"], unique=False)
    op.create_index(op.f("ix_teams_owner_user_id"), "teams", ["owner_user_id"], unique=False)
    op.create_index(
        "uq_teams_owner_name_lower",
        "teams",
        ["owner_user_id", sa.literal_column("lower(name)")],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )

    op.create_table(
        "tournaments",
        sa.Column("public_slug", sa.String(length=120), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "tournament_format",
            sa.Enum(
                "league",
                "group_knockout",
                "knockout",
                name="tournament_format",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "active",
                "completed",
                "archived",
                name="tournament_status",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("venue", sa.String(length=160), nullable=True),
        sa.Column("logo_url", sa.String(length=512), nullable=True),
        sa.Column("default_overs_limit", sa.SmallInteger(), nullable=True),
        sa.Column("default_max_overs_per_bowler", sa.SmallInteger(), nullable=True),
        sa.Column("points_per_win", sa.SmallInteger(), nullable=False),
        sa.Column("points_per_tie", sa.SmallInteger(), nullable=False),
        sa.Column("points_per_loss", sa.SmallInteger(), nullable=False),
        sa.Column("points_per_no_result", sa.SmallInteger(), nullable=False),
        sa.Column("use_net_run_rate", sa.Boolean(), nullable=False),
        sa.Column("teams_advancing_per_group", sa.SmallInteger(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "teams_advancing_per_group >= 1", name=op.f("ck_tournaments_advancing_positive")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_tournaments_created_by_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tournaments")),
        sa.UniqueConstraint("public_slug", name="uq_tournaments_public_slug"),
    )
    op.create_index(op.f("ix_tournaments_created_at"), "tournaments", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_tournaments_created_by_user_id"),
        "tournaments",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_tournaments_owner", "tournaments", ["created_by_user_id", "status"], unique=False
    )

    op.create_table(
        "players",
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "batter",
                "bowler",
                "allrounder",
                "wicket_keeper",
                "unknown",
                name="player_role",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "batting_hand",
            sa.Enum("right", "left", name="batting_hand", native_enum=False, length=40),
            nullable=True,
        ),
        sa.Column(
            "bowling_style",
            sa.Enum(
                "right_arm_fast",
                "right_arm_medium",
                "right_arm_off_spin",
                "right_arm_leg_spin",
                "left_arm_fast",
                "left_arm_medium",
                "left_arm_orthodox",
                "left_arm_chinaman",
                "unknown",
                name="bowling_style",
                native_enum=False,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("jersey_number", sa.SmallInteger(), nullable=True),
        sa.Column("sort_order", sa.SmallInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_players_team_id_teams"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_players")),
    )
    op.create_index(op.f("ix_players_created_at"), "players", ["created_at"], unique=False)
    op.create_index("ix_players_team_active", "players", ["team_id", "deleted_at"], unique=False)
    op.create_index(op.f("ix_players_team_id"), "players", ["team_id"], unique=False)

    op.create_table(
        "tournament_groups",
        sa.Column("tournament_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("ordinal", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournaments.id"],
            name=op.f("fk_tournament_groups_tournament_id_tournaments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tournament_groups")),
        sa.UniqueConstraint("tournament_id", "name", name="uq_tournament_groups_name"),
    )
    op.create_index(
        op.f("ix_tournament_groups_created_at"), "tournament_groups", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_tournament_groups_tournament_id"),
        "tournament_groups",
        ["tournament_id"],
        unique=False,
    )

    op.create_table(
        "matches",
        sa.Column("public_slug", sa.String(length=120), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("tournament_id", sa.UUID(), nullable=True),
        sa.Column("team_a_id", sa.UUID(), nullable=False),
        sa.Column("team_b_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=True),
        sa.Column("venue", sa.String(length=160), nullable=True),
        sa.Column("city", sa.String(length=80), nullable=True),
        sa.Column(
            "match_format",
            sa.Enum(
                "t20",
                "t10",
                "odi",
                "test",
                "box",
                "turf",
                "gully",
                "tape_ball",
                "tennis_ball",
                "custom",
                name="match_format",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "setup",
                "live",
                "innings_break",
                "completed",
                "abandoned",
                name="match_status",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("overs_limit", sa.SmallInteger(), nullable=True),
        sa.Column("balls_per_over", sa.SmallInteger(), nullable=False),
        sa.Column("players_per_side", sa.SmallInteger(), nullable=False),
        sa.Column("max_overs_per_bowler", sa.SmallInteger(), nullable=True),
        sa.Column("wide_penalty_runs", sa.SmallInteger(), nullable=False),
        sa.Column("no_ball_penalty_runs", sa.SmallInteger(), nullable=False),
        sa.Column("free_hit_after_no_ball", sa.Boolean(), nullable=False),
        sa.Column("allow_boundaries", sa.Boolean(), nullable=False),
        sa.Column("last_batter_can_bat_alone", sa.Boolean(), nullable=False),
        sa.Column("dls_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "rule_overrides",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("toss_winner_team_id", sa.UUID(), nullable=True),
        sa.Column(
            "toss_decision",
            sa.Enum("bat", "bowl", name="toss_decision", native_enum=False, length=40),
            nullable=True,
        ),
        sa.Column(
            "result_type",
            sa.Enum(
                "win",
                "tie",
                "draw",
                "no_result",
                "abandoned",
                "forfeit",
                "super_over",
                name="match_result_type",
                native_enum=False,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("winner_team_id", sa.UUID(), nullable=True),
        sa.Column("result_summary", sa.String(length=240), nullable=True),
        sa.Column("win_margin_runs", sa.SmallInteger(), nullable=True),
        sa.Column("win_margin_wickets", sa.SmallInteger(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("tournament_round", sa.String(length=40), nullable=True),
        sa.Column("tournament_group_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "balls_per_over BETWEEN 1 AND 12", name=op.f("ck_matches_balls_per_over_range")
        ),
        sa.CheckConstraint(
            "overs_limit IS NULL OR overs_limit > 0", name=op.f("ck_matches_overs_limit_positive")
        ),
        sa.CheckConstraint(
            "players_per_side BETWEEN 2 AND 15", name=op.f("ck_matches_players_per_side_range")
        ),
        sa.CheckConstraint("team_a_id <> team_b_id", name=op.f("ck_matches_teams_differ")),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_matches_created_by_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["team_a_id"], ["teams.id"], name=op.f("fk_matches_team_a_id_teams"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["team_b_id"], ["teams.id"], name=op.f("fk_matches_team_b_id_teams"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["toss_winner_team_id"],
            ["teams.id"],
            name=op.f("fk_matches_toss_winner_team_id_teams"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tournament_group_id"],
            ["tournament_groups.id"],
            name=op.f("fk_matches_tournament_group_id_tournament_groups"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournaments.id"],
            name=op.f("fk_matches_tournament_id_tournaments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["winner_team_id"],
            ["teams.id"],
            name=op.f("fk_matches_winner_team_id_teams"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_matches")),
        sa.UniqueConstraint("public_slug", name="uq_matches_public_slug"),
    )
    op.create_index(op.f("ix_matches_created_at"), "matches", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_matches_created_by_user_id"), "matches", ["created_by_user_id"], unique=False
    )
    op.create_index(
        "ix_matches_owner_status", "matches", ["created_by_user_id", "status"], unique=False
    )
    op.create_index(op.f("ix_matches_status"), "matches", ["status"], unique=False)
    op.create_index(op.f("ix_matches_team_a_id"), "matches", ["team_a_id"], unique=False)
    op.create_index(op.f("ix_matches_team_b_id"), "matches", ["team_b_id"], unique=False)
    op.create_index("ix_matches_tournament", "matches", ["tournament_id", "status"], unique=False)
    op.create_index(op.f("ix_matches_tournament_id"), "matches", ["tournament_id"], unique=False)

    op.create_table(
        "tournament_standings",
        sa.Column("tournament_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=True),
        sa.Column("played", sa.SmallInteger(), nullable=False),
        sa.Column("won", sa.SmallInteger(), nullable=False),
        sa.Column("lost", sa.SmallInteger(), nullable=False),
        sa.Column("tied", sa.SmallInteger(), nullable=False),
        sa.Column("no_result", sa.SmallInteger(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("runs_scored", sa.Integer(), nullable=False),
        sa.Column("overs_faced", sa.Numeric(precision=7, scale=3), nullable=False),
        sa.Column("runs_conceded", sa.Integer(), nullable=False),
        sa.Column("overs_bowled", sa.Numeric(precision=7, scale=3), nullable=False),
        sa.Column("net_run_rate", sa.Numeric(precision=7, scale=3), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["tournament_groups.id"],
            name=op.f("fk_tournament_standings_group_id_tournament_groups"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name=op.f("fk_tournament_standings_team_id_teams"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournaments.id"],
            name=op.f("fk_tournament_standings_tournament_id_tournaments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("tournament_id", "team_id", name=op.f("pk_tournament_standings")),
    )
    op.create_index(
        op.f("ix_tournament_standings_created_at"),
        "tournament_standings",
        ["created_at"],
        unique=False,
    )

    op.create_table(
        "tournament_teams",
        sa.Column("tournament_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=True),
        sa.Column("seed", sa.SmallInteger(), nullable=True),
        sa.Column("points_adjustment", sa.SmallInteger(), nullable=False),
        sa.Column("adjustment_note", sa.String(length=200), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["tournament_groups.id"],
            name=op.f("fk_tournament_teams_group_id_tournament_groups"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name=op.f("fk_tournament_teams_team_id_teams"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournaments.id"],
            name=op.f("fk_tournament_teams_tournament_id_tournaments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tournament_teams")),
        sa.UniqueConstraint("tournament_id", "team_id", name="uq_tournament_teams"),
    )
    op.create_index(
        op.f("ix_tournament_teams_created_at"), "tournament_teams", ["created_at"], unique=False
    )
    op.create_index(
        "ix_tournament_teams_group", "tournament_teams", ["tournament_id", "group_id"], unique=False
    )
    op.create_index(
        op.f("ix_tournament_teams_tournament_id"),
        "tournament_teams",
        ["tournament_id"],
        unique=False,
    )

    op.create_table(
        "bracket_matches",
        sa.Column("tournament_id", sa.UUID(), nullable=False),
        sa.Column(
            "round",
            sa.Enum(
                "round_of_16",
                "quarter_final",
                "semi_final",
                "third_place",
                "final",
                name="bracket_round",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("ordinal", sa.SmallInteger(), nullable=False),
        sa.Column("label", sa.String(length=60), nullable=True),
        sa.Column("team_a_id", sa.UUID(), nullable=True),
        sa.Column("team_b_id", sa.UUID(), nullable=True),
        sa.Column("source_a_bracket_id", sa.UUID(), nullable=True),
        sa.Column("source_b_bracket_id", sa.UUID(), nullable=True),
        sa.Column("source_a_label", sa.String(length=40), nullable=True),
        sa.Column("source_b_label", sa.String(length=40), nullable=True),
        sa.Column("match_id", sa.UUID(), nullable=True),
        sa.Column("winner_team_id", sa.UUID(), nullable=True),
        sa.Column("next_bracket_match_id", sa.UUID(), nullable=True),
        sa.Column("next_slot", sa.String(length=1), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "next_slot IS NULL OR next_slot IN ('a', 'b')",
            name=op.f("ck_bracket_matches_next_slot_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
            name=op.f("fk_bracket_matches_match_id_matches"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["next_bracket_match_id"],
            ["bracket_matches.id"],
            name=op.f("fk_bracket_matches_next_bracket_match_id_bracket_matches"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_a_bracket_id"],
            ["bracket_matches.id"],
            name=op.f("fk_bracket_matches_source_a_bracket_id_bracket_matches"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_b_bracket_id"],
            ["bracket_matches.id"],
            name=op.f("fk_bracket_matches_source_b_bracket_id_bracket_matches"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["team_a_id"],
            ["teams.id"],
            name=op.f("fk_bracket_matches_team_a_id_teams"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["team_b_id"],
            ["teams.id"],
            name=op.f("fk_bracket_matches_team_b_id_teams"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournaments.id"],
            name=op.f("fk_bracket_matches_tournament_id_tournaments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["winner_team_id"],
            ["teams.id"],
            name=op.f("fk_bracket_matches_winner_team_id_teams"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bracket_matches")),
        sa.UniqueConstraint("tournament_id", "ordinal", name="uq_bracket_matches_ordinal"),
    )
    op.create_index(
        op.f("ix_bracket_matches_created_at"), "bracket_matches", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_bracket_matches_tournament_id"),
        "bracket_matches",
        ["tournament_id"],
        unique=False,
    )

    op.create_table(
        "innings",
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.SmallInteger(), nullable=False),
        sa.Column("batting_team_id", sa.UUID(), nullable=False),
        sa.Column("bowling_team_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "in_progress",
                "completed",
                name="innings_status",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("overs_limit", sa.SmallInteger(), nullable=True),
        sa.Column("target_runs", sa.SmallInteger(), nullable=True),
        sa.Column("is_super_over", sa.Boolean(), nullable=False),
        sa.Column("is_follow_on", sa.Boolean(), nullable=False),
        sa.Column(
            "end_reason",
            sa.Enum(
                "overs_complete",
                "all_out",
                "target_reached",
                "declared",
                "rain",
                "forfeit",
                "other",
                name="innings_end_reason",
                native_enum=False,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("penalty_runs", sa.SmallInteger(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_delivery_seq", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "batting_team_id <> bowling_team_id", name=op.f("ck_innings_innings_teams_differ")
        ),
        sa.CheckConstraint("sequence BETWEEN 1 AND 8", name=op.f("ck_innings_sequence_range")),
        sa.ForeignKeyConstraint(
            ["batting_team_id"],
            ["teams.id"],
            name=op.f("fk_innings_batting_team_id_teams"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["bowling_team_id"],
            ["teams.id"],
            name=op.f("fk_innings_bowling_team_id_teams"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["match_id"], ["matches.id"], name=op.f("fk_innings_match_id_matches"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_innings")),
        sa.UniqueConstraint("match_id", "sequence", name="uq_innings_match_sequence"),
    )
    op.create_index(op.f("ix_innings_created_at"), "innings", ["created_at"], unique=False)
    op.create_index(op.f("ix_innings_match_id"), "innings", ["match_id"], unique=False)

    op.create_table(
        "match_collaborators",
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "owner",
                "scorer",
                "viewer",
                name="collaborator_role",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("invited_by_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"],
            ["users.id"],
            name=op.f("fk_match_collaborators_invited_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
            name=op.f("fk_match_collaborators_match_id_matches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_match_collaborators_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_collaborators")),
        sa.UniqueConstraint("match_id", "user_id", name="uq_match_collaborators"),
    )
    op.create_index(
        op.f("ix_match_collaborators_created_at"),
        "match_collaborators",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_match_collaborators_match_id"), "match_collaborators", ["match_id"], unique=False
    )
    op.create_index(
        op.f("ix_match_collaborators_user_id"), "match_collaborators", ["user_id"], unique=False
    )

    op.create_table(
        "match_players",
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("batting_order", sa.SmallInteger(), nullable=False),
        sa.Column("is_captain", sa.Boolean(), nullable=False),
        sa.Column("is_wicket_keeper", sa.Boolean(), nullable=False),
        sa.Column("is_playing", sa.Boolean(), nullable=False),
        sa.Column("is_substitute", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "batting_order BETWEEN 1 AND 20", name=op.f("ck_match_players_batting_order_range")
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
            name=op.f("fk_match_players_match_id_matches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_match_players_player_id_players"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name=op.f("fk_match_players_team_id_teams"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_players")),
        sa.UniqueConstraint("match_id", "team_id", "batting_order", name="uq_match_players_order"),
    )
    op.create_index(
        op.f("ix_match_players_created_at"), "match_players", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_match_players_match_id"), "match_players", ["match_id"], unique=False)
    op.create_index(
        "ix_match_players_match_team", "match_players", ["match_id", "team_id"], unique=False
    )

    op.create_table(
        "deliveries",
        sa.Column("innings_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("striker_id", sa.UUID(), nullable=False),
        sa.Column("non_striker_id", sa.UUID(), nullable=False),
        sa.Column("bowler_id", sa.UUID(), nullable=False),
        sa.Column("batter_runs", sa.SmallInteger(), nullable=False),
        sa.Column(
            "extra_type",
            sa.Enum(
                "wide",
                "no_ball",
                "bye",
                "leg_bye",
                "penalty",
                name="extra_type",
                native_enum=False,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("extra_runs", sa.SmallInteger(), nullable=False),
        sa.Column("is_boundary", sa.Boolean(), nullable=False),
        sa.Column("batters_crossed", sa.Boolean(), nullable=True),
        sa.Column("is_wicket", sa.Boolean(), nullable=False),
        sa.Column(
            "wicket_type",
            sa.Enum(
                "bowled",
                "caught",
                "caught_and_bowled",
                "lbw",
                "stumped",
                "hit_wicket",
                "run_out",
                "obstructing_the_field",
                "hit_ball_twice",
                "timed_out",
                "retired_out",
                "retired_hurt",
                name="wicket_type",
                native_enum=False,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("dismissed_player_id", sa.UUID(), nullable=True),
        sa.Column("fielder_id", sa.UUID(), nullable=True),
        sa.Column("replacement_batter_id", sa.UUID(), nullable=True),
        sa.Column("commentary", sa.Text(), nullable=True),
        sa.Column("revision", sa.SmallInteger(), nullable=False),
        sa.Column("recorded_by_user_id", sa.UUID(), nullable=True),
        sa.Column("client_event_id", sa.UUID(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "(is_wicket = false AND wicket_type IS NULL) OR "
            "(is_wicket = true AND wicket_type IS NOT NULL)",
            name=op.f("ck_deliveries_wicket_type_requires_wicket"),
        ),
        sa.CheckConstraint(
            "batter_runs BETWEEN 0 AND 12", name=op.f("ck_deliveries_batter_runs_range")
        ),
        sa.CheckConstraint(
            "extra_runs BETWEEN 0 AND 12", name=op.f("ck_deliveries_extra_runs_range")
        ),
        sa.CheckConstraint(
            "striker_id <> non_striker_id", name=op.f("ck_deliveries_batters_differ")
        ),
        sa.ForeignKeyConstraint(
            ["bowler_id"],
            ["match_players.id"],
            name=op.f("fk_deliveries_bowler_id_match_players"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["dismissed_player_id"],
            ["match_players.id"],
            name=op.f("fk_deliveries_dismissed_player_id_match_players"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["fielder_id"],
            ["match_players.id"],
            name=op.f("fk_deliveries_fielder_id_match_players"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["innings_id"],
            ["innings.id"],
            name=op.f("fk_deliveries_innings_id_innings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["non_striker_id"],
            ["match_players.id"],
            name=op.f("fk_deliveries_non_striker_id_match_players"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_user_id"],
            ["users.id"],
            name=op.f("fk_deliveries_recorded_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["replacement_batter_id"],
            ["match_players.id"],
            name=op.f("fk_deliveries_replacement_batter_id_match_players"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["striker_id"],
            ["match_players.id"],
            name=op.f("fk_deliveries_striker_id_match_players"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deliveries")),
        # Idempotency: replaying an offline queue can never double-count a ball.
        sa.UniqueConstraint("innings_id", "client_event_id", name="uq_deliveries_client_event"),
        sa.UniqueConstraint("innings_id", "sequence", name="uq_deliveries_innings_sequence"),
    )
    op.create_index(op.f("ix_deliveries_created_at"), "deliveries", ["created_at"], unique=False)
    op.create_index(op.f("ix_deliveries_innings_id"), "deliveries", ["innings_id"], unique=False)
    op.create_index(
        "ix_deliveries_innings_seq", "deliveries", ["innings_id", "sequence"], unique=False
    )

    op.create_table(
        "delivery_revisions",
        sa.Column("delivery_id", sa.UUID(), nullable=False),
        sa.Column("innings_id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.SmallInteger(), nullable=False),
        sa.Column("change_kind", sa.String(length=16), nullable=False),
        sa.Column("previous_state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("new_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reason", sa.String(length=240), nullable=True),
        sa.Column("changed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["changed_by_user_id"],
            ["users.id"],
            name=op.f("fk_delivery_revisions_changed_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["innings_id"],
            ["innings.id"],
            name=op.f("fk_delivery_revisions_innings_id_innings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery_revisions")),
    )
    op.create_index(
        op.f("ix_delivery_revisions_created_at"), "delivery_revisions", ["created_at"], unique=False
    )
    op.create_index(
        "ix_delivery_revisions_delivery",
        "delivery_revisions",
        ["delivery_id", "revision"],
        unique=False,
    )
    op.create_index(
        op.f("ix_delivery_revisions_delivery_id"),
        "delivery_revisions",
        ["delivery_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_delivery_revisions_innings_id"), "delivery_revisions", ["innings_id"], unique=False
    )

    op.create_table(
        "innings_summaries",
        sa.Column("innings_id", sa.UUID(), nullable=False),
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("batting_team_id", sa.UUID(), nullable=False),
        sa.Column("bowling_team_id", sa.UUID(), nullable=False),
        sa.Column("total_runs", sa.Integer(), nullable=False),
        sa.Column("total_wickets", sa.SmallInteger(), nullable=False),
        sa.Column("legal_balls", sa.Integer(), nullable=False),
        sa.Column("overs_text", sa.String(length=12), nullable=False),
        sa.Column("nrr_overs", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column("extras_wide", sa.SmallInteger(), nullable=False),
        sa.Column("extras_no_ball", sa.SmallInteger(), nullable=False),
        sa.Column("extras_bye", sa.SmallInteger(), nullable=False),
        sa.Column("extras_leg_bye", sa.SmallInteger(), nullable=False),
        sa.Column("extras_penalty", sa.SmallInteger(), nullable=False),
        sa.Column("run_rate", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column("is_all_out", sa.Boolean(), nullable=False),
        sa.Column("delivery_count", sa.Integer(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["batting_team_id"],
            ["teams.id"],
            name=op.f("fk_innings_summaries_batting_team_id_teams"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["bowling_team_id"],
            ["teams.id"],
            name=op.f("fk_innings_summaries_bowling_team_id_teams"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["innings_id"],
            ["innings.id"],
            name=op.f("fk_innings_summaries_innings_id_innings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
            name=op.f("fk_innings_summaries_match_id_matches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("innings_id", name=op.f("pk_innings_summaries")),
    )
    op.create_index(
        op.f("ix_innings_summaries_created_at"), "innings_summaries", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_innings_summaries_match_id"), "innings_summaries", ["match_id"], unique=False
    )


def downgrade() -> None:
    op.drop_table("innings_summaries")
    op.drop_table("delivery_revisions")
    op.drop_table("deliveries")
    op.drop_table("match_players")
    op.drop_table("match_collaborators")
    op.drop_table("innings")
    op.drop_table("bracket_matches")
    op.drop_table("tournament_teams")
    op.drop_table("tournament_standings")
    op.drop_table("matches")
    op.drop_table("tournament_groups")
    op.drop_table("players")
    op.drop_table("tournaments")
    op.drop_table("teams")
    op.drop_table("refresh_tokens")
    op.drop_table("audit_logs")
    op.drop_table("users")
